name: jsonify
description: >
  A library useful for objects to serialize it and make a json represention of it.
version: 0.1.0
author: Joris Hermans <hermansj@gmail.com>
homepage: https://github.com/jorishermans/jsonify
dev_dependencies:
  test: any
